include:
  - local: '/build.yml'
  - local: '/tests.yml'

stages:
  - build
  - test
  - release
  - renovate

build:
  extends: .build
  stage: build
  image: docker:20.10
  script:
    - build_image_legacy /build/docker

container_scanning:
  stage: test
  extends: .container_scanning
  variables:
    SUB_IMAGE_NAME: /build/docker

release:
  extends: .build
  stage: release
  image: docker:20.10
  script:
    - release_latest /build/docker
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - when: never

.renovate:
  variables:
    RENOVATE_GIT_AUTHOR: "${GITLAB_USER_NAME} <${GITLAB_USER_EMAIL}>"
    RENOVATE_DRY_RUN: "false"
    LOG_LEVEL: "info"
  image:
    name: renovate/renovate:32.21
    entrypoint: [""]
  dependencies: []
  needs: []
  script:
    - >
      renovate
      --autodiscover="true"
      --platform "gitlab"
      --endpoint "${CI_API_V4_URL}"
      --git-author "${RENOVATE_GIT_AUTHOR}"
      --dry-run "${RENOVATE_DRY_RUN}"
      "${CI_PROJECT_PATH}"
  rules:
    - when: manual
    - if: $CI_PIPELINE_SOURCE == "schedule"

renovate:
  extends: .renovate
  stage: renovate
