include:
  - local: '/build.yml'
  - local: '/tests.yml'
  - local: '/k3d.yml'
  - local: '/workflow.yml'

stages:
  - build
  - test
  - release
  - renovate

build:
  extends: .build
  stage: build
  image: docker:23.0
  script:
    - build_image_legacy /build/docker

container_scanning:
  stage: test
  extends: .container_scanning
  variables:
    SUB_IMAGE_NAME: /build/docker

release:
  extends: .build
  stage: release
  image: "registry.gitlab.com/strowi/ci-templates/build/docker:master"
  script:
    - release_latest /build/docker
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - when: never

.renovate:
  variables:
    RENOVATE_GIT_AUTHOR: "${GITLAB_USER_NAME} <${GITLAB_USER_EMAIL}>"
    RENOVATE_DRY_RUN: false
    LOG_LEVEL: "info"
  image:
    name: renovate/renovate:35.66
    entrypoint: [""]
  dependencies: []
  needs: []
  script:
    - >
      renovate
      --autodiscover="true"
      --platform "gitlab"
      --endpoint "${CI_API_V4_URL}"
      --git-author "${RENOVATE_GIT_AUTHOR}"
      --dry-run "${RENOVATE_DRY_RUN}"
      "${CI_PROJECT_PATH}"
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - when: manual

renovate:
  extends: .renovate
  stage: renovate



deploy-tests:
  stage: test
  extends: .k3d
  environment: ci
  script:
    - start_k3d
    - deploy-k8
    - get_pod nginx-krane
    # - deploy-helm
    # - get_pod nginx-helm
    - kubectl get deploy,po --all-namespaces
  parallel:
    matrix:
      - K3S_VERSION:
        - v1.25.10-k3s1
