include:
  - local: '/build.yml'
  - local: '/tests.yml'

stages:
  - build
  - test
  - renovate
  - release

build:
  extends: .build
  stage: build
  script:
    - build_image
  variables:
    SUB_IMAGE_NAME: /build/docker


container_scanning:
  stage: test
  extends: .container_scanning
  variables:
    SUB_IMAGE_NAME: /build/docker

release:
  extends: .build
  stage: release
  script:
    - release_latest

.renovate:
  variables:
    RENOVATE_GIT_AUTHOR: "${GITLAB_USER_NAME} <${GITLAB_USER_EMAIL}>"
    RENOVATE_DRY_RUN: "false"
    LOG_LEVEL: "info"
  image:
    name: renovate/renovate:32.21
    entrypoint: [""]
  dependencies: []
  needs: []
  script:
    - >
      renovate
      --autodiscover="true"
      --platform "gitlab"
      --endpoint "${CI_API_V4_URL}"
      --git-author "${RENOVATE_GIT_AUTHOR}"
      --dry-run "${RENOVATE_DRY_RUN}"
      "${CI_PROJECT_PATH}"
  only:
    - master
    - schedules

renovate:
  extends: .renovate
  stage: renovate
